// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
import { ReactNode } from "react";
import LayoutClient from "./LayoutClient";
import { getSideBarProp } from "@/utils/generalUtils";

export default async function VidPage({ children }: { children: ReactNode }) {
  // const sidebarProp = await getSideBarProp();
  // const categoriesList = sidebarProp["category_prop"];
  // const tagsList = sidebarProp["tag_prop"];
  return (
    <LayoutClient>
      {children}
    </LayoutClient>
  );
}
